/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import dao.PCD;
import dao.PCDDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author leoomoreira
 */
public class OpcoesSistema extends javax.swing.JFrame {

    /**
     * Creates new form TelaInserirPessoa
     */
    public OpcoesSistema() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoAlterarDados = new javax.swing.JButton();
        botaoNovaSolicitacao = new javax.swing.JButton();
        botaoAcompSolicitacao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Pessoa");
        setName("dialogInserirPessoa"); // NOI18N

        botaoAlterarDados.setText("Alterar Dados");
        botaoAlterarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarDadosActionPerformed(evt);
            }
        });

        botaoNovaSolicitacao.setText("Nova Solicitação");
        botaoNovaSolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovaSolicitacaoActionPerformed(evt);
            }
        });

        botaoAcompSolicitacao.setText("Acompanhar Solicitação");
        botaoAcompSolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAcompSolicitacaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Escolha a opção desejada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoNovaSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(botaoAcompSolicitacao)
                        .addGap(29, 29, 29)
                        .addComponent(botaoAlterarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAlterarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAcompSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoNovaSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAlterarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarDadosActionPerformed
        new alterarDados().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAlterarDadosActionPerformed

    private void botaoNovaSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovaSolicitacaoActionPerformed
        // TODO add your handling code here:
        new NovaSolicitacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoNovaSolicitacaoActionPerformed

    private void botaoAcompSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAcompSolicitacaoActionPerformed
        // TODO add your handling code here:
        new AcompanharSolicitacoes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoAcompSolicitacaoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAcompSolicitacao;
    private javax.swing.JButton botaoAlterarDados;
    private javax.swing.JButton botaoNovaSolicitacao;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
