/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import dao.PCD;
import dao.PCDDAO;
import dao.novaSolicitacao;
import javax.swing.JOptionPane;

/**
 *
 * @author leoomoreira
 */
public class NovaSolicitacao extends javax.swing.JDialog {

    /**
     * Creates new form TelaInserirPessoa
     */
    public NovaSolicitacao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotuloCodigo = new javax.swing.JLabel();
        rotuloNome = new javax.swing.JLabel();
        rotuloLogin = new javax.swing.JLabel();
        textoTituloObra = new javax.swing.JTextField();
        textoAutorObra = new javax.swing.JTextField();
        textoObservacoes = new javax.swing.JTextField();
        botaoEnviar = new javax.swing.JButton();
        rotuloLogin1 = new javax.swing.JLabel();
        comboFormatoAcessivel = new javax.swing.JComboBox();
        tituloNovaSolicitacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Pessoa");
        setName("dialogInserirPessoa"); // NOI18N

        rotuloCodigo.setText("Título da Obra:");

        rotuloNome.setText("Autor da Obra:");

        rotuloLogin.setText("Observações:");

        textoObservacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoObservacoesActionPerformed(evt);
            }
        });

        botaoEnviar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoEnviar.setText("Enviar");
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });

        rotuloLogin1.setText("Formato Acessível Desejado:");

        comboFormatoAcessivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboFormatoAcessivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFormatoAcessivelActionPerformed(evt);
            }
        });

        tituloNovaSolicitacao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tituloNovaSolicitacao.setText("Nova Solicitação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoEnviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rotuloLogin1)
                            .addGap(18, 18, 18)
                            .addComponent(comboFormatoAcessivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(rotuloCodigo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textoTituloObra))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(rotuloNome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textoAutorObra))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(rotuloLogin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(textoObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloNovaSolicitacao)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(tituloNovaSolicitacao)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotuloCodigo)
                    .addComponent(textoTituloObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotuloNome)
                    .addComponent(textoAutorObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotuloLogin)
                    .addComponent(textoObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotuloLogin1)
                    .addComponent(comboFormatoAcessivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(botaoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        textoTituloObra.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente enviar essa solicitação?", "Nova Solicitação", JOptionPane.YES_NO_CANCEL_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {
            try {
                novaSolicitacao ns = new novaSolicitacao();
                p.setMatricula(Integer.parseInt(textoTituloObra.getText()));
                p.setNome(textoAutorObra.getText());
                p.setCurso(textoObservacoes.getText());
                p.setUA(comboFormatoAcessivel.get());
                p.setCondicao_deficiencia(textoCondicao_deficiencia.getText());
                p.setTelefone(Integer.parseInt(textoTelefone.getText()));
                p.setEmail(textoEmail.getText());
                p.setSenha(textoSenha.getText());

                JOptionPane.showMessageDialog(this, "Pessoa inserida com sucesso", "Nova Solicitação", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Nova Solicitação", JOptionPane.ERROR_MESSAGE);
            }
        }
        botaoEnviar.transferFocus();
    }//GEN-LAST:event_botaoEnviarActionPerformed

    private void comboFormatoAcessivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFormatoAcessivelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboFormatoAcessivelActionPerformed

    private void textoObservacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoObservacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoObservacoesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JComboBox comboFormatoAcessivel;
    private javax.swing.JLabel rotuloCodigo;
    private javax.swing.JLabel rotuloLogin;
    private javax.swing.JLabel rotuloLogin1;
    private javax.swing.JLabel rotuloNome;
    private javax.swing.JTextField textoAutorObra;
    private javax.swing.JTextField textoObservacoes;
    private javax.swing.JTextField textoTituloObra;
    private javax.swing.JLabel tituloNovaSolicitacao;
    // End of variables declaration//GEN-END:variables
}
